sudo: required
language: node_js
node_js:
  - 9.1.0
  - 10
scripts:
  - yarn install
  - yarn start
cache:
    yarn: true
    directories:
      - node_modules
notifications:
    email: false
